### ISSUE TITLE
Step 0: 좋은 소프트웨어, 좋은 개발자란 무엇인가

### ISSUE THREAD

**Issue by headF1rst** [DKU-SPRINGLES/Basic-Java-Study#2]
## 학습 목표
다른 사람들이 생각하는 좋은 소프트웨어란 무엇이고, 좋은 개발자란 무엇인지에 관련된 영상 혹은 포스트를 하나 찾아보고 링크 공유하기

## 학습할 것
- 링크를 올리고나서 다른 스터디원이 올린 링크도 한번 보기
- `객체 지향의 사실과 오해` 책 도서관에서 대여해서 읽기
  - http://www.yes24.com/Product/Goods/18249021

## 마감일시
2022년 07월 19일 23시
(책 읽기는 08월 01일 까지)

**Comment by headF1rst** [comment]
## EX)
Step0 과제 제출하도록 하겠습니다! 

- [클놈 코딩](https://www.youtube.com/watch?v=PEGPnZ_nEjU)
- ...
- [라인 개발자들이 쓰는 키보드는?](https://www.youtube.com/watch?v=8u3KRK2_X1c&t=286s) 😎

**Comment by kim-hani** [comment]
Step0 과제 제출입니다!

저는 아직 개발에 대한 지식이 많이 부족하고 어떠한 과정으로 개발 공부를 해야하는지 잘 파악하지 못하고 있습니다.
하지만  주변사람들 혹은 멘토들의 공부 방법이나 조언들을 듣고 나에게 대입해보며 나의 부족함을 되돌아볼 수 있다면 
저는 반드시 성장 할 수 있을 것이라고 생각합니다.
트랜드는 빠르게 바뀌며 고객들은 더 편하고 좋은 서비스를 원합니다. 이렇게 빠른 흐름에 적응하고 남들보다 더 나아가기 위해서는 저희는 꾸준히 성장해야 합니다. 
이런 이유로 저는 성장하는 개발자가 좋은 개발자라 생각하고 이에 대한 팁을 제공하는 영상의 링크를 공유합니다.

- [좋은 소프트웨어의 기본](https://whoishoo.tistory.com/175)

- [드림 코딩/성장하는 개발자](https://www.youtube.com/watch?v=T7y6Hl0YZ14)

**Comment by headF1rst** [comment]
> Step0 과제 제출입니다!
> 
> 저는 아직 개발에 대한 지식이 많이 부족하고 어떠한 과정으로 개발 공부를 해야하는지 잘 파악하지 못하고 있습니다. 하지만 주변사람들 혹은 멘토들의 공부 방법이나 조언들을 듣고 나에게 대입해보며 나의 부족함을 되돌아볼 수 있다면 저는 반드시 성장 할 수 있을 것이라고 생각합니다. 트랜드는 빠르게 바뀌며 고객들은 더 편하고 좋은 서비스를 원합니다. 이렇게 빠른 흐름에 적응하고 남들보다 더 나아가기 위해서는 저희는 꾸준히 성장해야 합니다. 이런 이유로 저는 성장하는 개발자가 좋은 개발자라 생각하고 이에 대한 팁을 제공하는 영상의 링크를 공유합니다.
> 
> * [좋은 소프트웨어의 기본](https://whoishoo.tistory.com/175)
> * [드림 코딩/성장하는 개발자](https://www.youtube.com/watch?v=T7y6Hl0YZ14)

좋은 마인드네요!
빠른 흐름에 적응해야하는건 저희도 그렇지만 소프트웨어도 마찬가지라고 생각합니다.
개발한 서비스가 사용자들의 요구사항을 빠르게 반영하지 못하고 기능 하나를 추가하거나 수정할때 마다 에러가 몇개씩 터진다면, 사용자들은 하나둘씩 서비스를 외면하기 시작하겠죠.
그렇기 때문에 빠른 기능구현 만을 위한 코드가 아닌 유지보수와 확장 가능성을 고려한 코드를 작성하기 위해선 무엇이 필요한지 생각해보시면 좋을것 같아요.

앞으로 많은 선배와 멘토를 만날 기회가 있을텐데요.
뭔가를 배웠을때 “00선배가 알려줬으니까 맞는 내용이겠지” 하고 넘어가지 마시고, 스스로 한번쯤은 다시 찾아보는 습관을 가지셨으면 좋겠습니다.
(저도 가끔 잘못된 내용을 알려줄 수 있는데요. 잘못된 정보가 있으면 역으로 피드백 해주시면 감사하겠습니다.)
