### ISSUE TITLE
Step 1: JVM은 무엇이며 자바 코드는 어떻게 동작하는 것인가.

### ISSUE THREAD

**Issue by headF1rst** [DKU-SPRINGLES/Basic-Java-Study#3]
## 학습 목표
자바 소스 파일 (.java)을 JVM으로 실행하는 과정 공부하기.

## 학습할 것
- JVM이란 무엇인가
  - JVM의 구성요소 알아보기
 - 컴파일 하는 방법
 - 실행하는 방법
 - 바이트코드란 무엇인가
 - JIT 컴파일러란 무엇인가, 어떻게 동작하는지
 - JDK와 JRE의 차이

## Optional
- JVM 구성요소 중 Heap의 구성요소에 대해서 좀 더 자세히 알아보기
- Garbage Collector가 무엇인지 알아보기

## 마감 일시
2022년 07월 20일 23시

**Comment by kim-hani** [comment]
Step.01 과제 제출하겠습니다!
과제 내용에 대한 글을 블로그에 작성했습니다

* [JVM이란 무엇인가](https://velog.io/@h_ani99/Java-JVM%EC%9D%B4%EB%9E%80-%EB%AC%B4%EC%97%87%EC%9D%B8%EA%B0%80)

**Comment by headF1rst** [comment]
블로그 가독성 좋게 잘 작성했네요!
지금 단계에선 어려울 수 있지만 시간 되시면 `Minor GC`, `Major GC`, `Full GC`에 대해 찾아보시는 것도 좋을것 같습니다.

**Comment by headF1rst** [comment]
> Step.01 과제 제출하겠습니다! 과제 내용에 대한 글을 블로그에 작성했습니다
> 
> * [JVM이란 무엇인가](https://velog.io/@h_ani99/Java-JVM%EC%9D%B4%EB%9E%80-%EB%AC%B4%EC%97%87%EC%9D%B8%EA%B0%80)

블로그 가독성 좋게 잘 작성했네요!
지금 단계에선 어려울 수 있지만 시간 되시면 `Minor GC`, `Major GC`, `Full GC`에 대해 찾아보시는 것도 좋을것 같습니다.
