### ISSUE TITLE
Step 2: 자바 데이터 타입, 변수 그리고 배열에 대해서 알아보기

### ISSUE THREAD

**Issue by headF1rst** [DKU-SPRINGLES/Basic-Java-Study#4]
## 학습 목표
자바의 프리미티브 타입, 변수 그리고 배열을 사용하는 방법 공부하기.

## 학습할 것
- 프리미티브 타입 종류와 값의 범위 그리고 기본 값
- 프리미티브 타입과 레퍼런스 타입
- 리터럴
- 변수 선언 및 초기화하는 방법
- 변수의 스코프와 라이프타임
- 타입 변환, 캐스팅 그리고 타입 프로모션
- 1차 및 2차 배열 선언하기
- 타입 추론, var

## 마감 일시
2022년 07월 22일 23시

**Comment by kim-hani** [comment]
Step 2  과제 제출입니다!
- [자바 데이터 타입,변수, 그리고 배열](https://velog.io/@h_ani99/JAVA-Primitive-%ED%83%80%EC%9E%85%EB%B3%80%EC%88%98-%EA%B7%B8%EB%A6%AC%EA%B3%A0-%EB%B0%B0%EC%97%B4)

**Comment by headF1rst** [comment]
> Step 2 과제 제출입니다!
> 
> * [자바 데이터 타입,변수, 그리고 배열](https://velog.io/@h_ani99/JAVA-Primitive-%ED%83%80%EC%9E%85%EB%B3%80%EC%88%98-%EA%B7%B8%EB%A6%AC%EA%B3%A0-%EB%B0%B0%EC%97%B4)

굿굿! 기회가 된다면 공유 데이터를 사용함으로서 주의해야할 점이나 static 멤버를 사용함에 있어서 주의할 점 등을 알아보면 좋을것 같습니다
