### ISSUE TITLE
Step 4: 제어문

### ISSUE THREAD

**Issue by headF1rst** [DKU-SPRINGLES/Basic-Java-Study#6]
## 학습 목표
자바가 제공하는 제어문 공부하기.

## 학습할 것
- 선택문
- 반복문

## 마감 일시
2022년 07월 28일 23시

**Comment by kim-hani** [comment]
4주차 과제 제출입니다!

- [제어문](https://velog.io/@h_ani99/JAVA-%EC%A0%9C%EC%96%B4%EB%AC%B8)

**Comment by headF1rst** [comment]
> 4주차 과제 제출입니다!
> 
> * [제어문](https://velog.io/@h_ani99/JAVA-%EC%A0%9C%EC%96%B4%EB%AC%B8)

정리 잘해줬네요!! 💯
else문 관련해서 참고할 만한 포스트이니 꼭 한번 읽어보면 좋겠습니다.
https://7942yongdae.tistory.com/11
https://tecoble.techcourse.co.kr/post/2020-07-29-dont-use-else/
