### ISSUE TITLE
Step 5: 클래스

### ISSUE THREAD

**Issue by headF1rst** [DKU-SPRINGLES/Basic-Java-Study#7]
## 학습 목표
자바가 제공하는 제어문 공부하기.

## 학습할 것
- 클래스 정의하는 방법
- 객체 생성 방법 (new 키워드 이해하기)
- 메서드 정의하는 방법
- 생성자 정의하는 방법
- this 키워드 이해하기

## 마감 일시
2022년 08월 2일 23시

**Comment by kim-hani** [comment]
5주차 과제 제출입니다!

- [클래스](https://velog.io/@h_ani99/JAVA-%ED%81%B4%EB%9E%98%EC%8A%A4)
