### ISSUE TITLE
Step 6: 상속

### ISSUE THREAD

**Issue by headF1rst** [DKU-SPRINGLES/Basic-Java-Study#8]
## 학습 목표
자바의 상속에 대해 공부하기.

## 학습할 것
- 자바 상속의 특징
- super 키워드
- 메서드 오버라이딩
- 다이나믹 메서드 디스패치 (Dynamic Method Dispatch)
- 추상 클래스 (abstract)
- final 키워드
- Object 클래스

## 마감 일시
2022년 08월 11일 23시

**Comment by kim-hani** [comment]
6주차 과제 제출입니다!


[상속](https://velog.io/@h_ani99/JAVA-%EC%83%81%EC%86%8D#24-%EA%B0%9D%EC%B2%B4%EC%9D%98-%ED%83%80%EC%9E%85-%EB%B3%80%ED%99%98)

**Comment by headF1rst** [comment]
> 상속

자바가 다중 상속을 허용하지 않는 이유와 다형성에 대해 잘 설명해 주셨네요 💯
Equals & hashCode의 경우도 중요한 개념이기 때문에 잘 공부해 두시면 도움이 될것 같습니다.
