### ISSUE TITLE
Step 7: 패키지

### ISSUE THREAD

**Issue by headF1rst** [DKU-SPRINGLES/Basic-Java-Study#9]
## 학습 목표
자바 패키지에 대해 공부하기.

## 학습할 것
- package 키워드
- import 키워드
- 클래스패스
- CLASSPATH 환경변수
- -classpath 옵션
- 접근지시자

## 마감 일시
2022년 08월 14일 23시

**Comment by kim-hani** [comment]
7주차 과제 제출입니다!

[패키지](https://velog.io/@h_ani99/JAVA-%ED%8C%A8%ED%82%A4%EC%A7%80)

**Comment by headF1rst** [comment]
> 7주차 과제 제출입니다!
> 
> [패키지](https://velog.io/@h_ani99/JAVA-%ED%8C%A8%ED%82%A4%EC%A7%80)

블로그 글의 가독성이 점점 좋아지는것 같네요! 
주제와 상관없는 내용이지만 몇몇 예제에서 필드값을 `public`으로 선언하였는데, 객체지향적인 관점에서 클래스의 필드값을 왜 `private` 으로 선언하는지  한번 알아보면 좋을것 같아요!
